# Generated by Django 5.0.7 on 2024-08-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_links_app', '0002_link_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='shortened_path',
        ),
    ]
